apiVersion: machineconfiguration.uccp.io/v1
kind: MachineConfigPool
metadata:
  name: etcd
  namespace: kube-system
spec:
  machineConfigSelector:
    matchLabels:
      "machineconfiguration.uccp.io/role": "etcd"
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/etcd: ""