apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: machine-config-daemon
  namespace: uccp-machine-config-operator
  labels:
    k8s-app: machine-config-daemon
  annotations:
    include.release.uccp.io/self-managed-high-availability: "true"
    include.release.uccp.io/single-node-developer: "true"
spec:
  endpoints:
  - interval: 30s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: metrics
    scheme: https
    path: /metrics
    relabelings:
    - action: replace
      regex: ;(.*)
      replacement: $1
      separator: ";"
      sourceLabels:
      - node
      - __meta_kubernetes_pod_node_name
      targetLabel: node
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: machine-config-daemon.uccp-machine-config-operator.svc
  namespaceSelector:
    matchNames:
    - uccp-machine-config-operator
  selector:
    matchLabels:
      k8s-app: machine-config-daemon
