---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-account-uccp-machine-config-operator
  annotations:
    include.release.uccp.io/ibm-cloud-managed: "true"
    include.release.uccp.io/self-managed-high-availability: "true"
    include.release.uccp.io/single-node-developer: "true"
subjects:
- kind: ServiceAccount
  name: default
  namespace: uccp-machine-config-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# Role for accessing metrics exposed by MCD in MCO namepsace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: uccp-machine-config-operator
  annotations:
    include.release.uccp.io/ibm-cloud-managed: "true"
    include.release.uccp.io/self-managed-high-availability: "true"
    include.release.uccp.io/single-node-developer: "true"
rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
---
# Grant cluster-monitoring access to MCD metrics in MCO namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: uccp-machine-config-operator
  annotations:
    include.release.uccp.io/ibm-cloud-managed: "true"
    include.release.uccp.io/self-managed-high-availability: "true"
    include.release.uccp.io/single-node-developer: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: uccp-monitoring
